### ISSUE TITLE
Error with mdash

### ISSUE THREAD

**Issue by reagle** [daryltucker/MagiclessQuotes#4]
I'm running ST3 3070 with a bunch of plugins (is there a way to list those for debugging purposes?). In any case, when I save the following text:

> Alas, as much as I try to understand other people’s perspectives, the first reference to my "male privilege”—my privilege!—is approximately where I get off the train, because it’s so alien to my actual lived experience. This is not, insanely, to suggest a lack of misogyny in the modern world! To whatever extent there is misogyny, one could say that there’s also "male privilege.” Rather it’s to suggest that, given what nerdy males have themselves had to endure in life, shaming them over their "male privilege” is a bad way to begin a conversation with them. 

You can see it messes up on the mdashes:

> Alas, as much as I try to understand other people's perspectives, the first reference to my "male priv---lege"—my pr---vilege!—is approximately where I get off the train, because it's so alien to my actual lived experience. This is not, insanely, to suggest a lack of misogyny in the modern world! To whatever extent there is misogyny, one could say that there's also "male privilege." Rather it's to suggest that, given what nerdy males have themselves had to endure in life, shaming them over their "male privilege" is a bad way to begin a conversation with them.

**Comment by daryltucker** [comment]
Thanks so much for taking the time to report this issue and provide such a clear example.  I'll have to take a look.

I'm not familiar with 3070, but you can see your installed packes by listing the `~/.config/sublime-text-3-/Installed Packeges/` directory, or, if you're using [Package Control](https://packagecontrol.io), you can take a look at `~/.config/sublime-text-3/Packages/User/Package\ Control.sublime-settings`, directly.

**Comment by reagle** [comment]
```
        "installed_packages":
        [
                "dired",
                "File History",
                "Filter Lines",
                "GitGutter",
                "Ignore Words",
                "Keymaps",
                "MarkdownEditing",
                "Mediawiker",
                "Modific",
                "Origami",
                "Package Control",
                "RegReplace",
                "SideBarEnhancements",
                "SideBarFolders",
                "SublimeGit",
                "Table Editor",
                "Terminal"
        ],
```

**Comment by reagle** [comment]
BTW: I also have manually installed the code suggested in https://www.sublimetext.com/forum/viewtopic.php?f=3&t=14451 and it has the same bug with mdash. Maybe it's some sort of regex bug in ST3?

**Comment by daryltucker** [comment]
Well, I can confirm that the addon works in ST3, but it seems like you're having a compatibility issue with another plugin.  I run Linux, so I guess it could technically be an OS issue, too.

**Comment by reagle** [comment]
Sublime text 3071 on Kubuntu 14.04. I removed all package except the following and still have the bug.

```
	"installed_packages":
	[
		"MagiclessQuotes",
		"Package Control"
	],
```

**Comment by daryltucker** [comment]
Give [Package Control](https://packagecontrol.io/) some time to pull in the changes.

Please let me know if you still have issues or if you find any additional problems!

**Comment by reagle** [comment]
I see it in package control and downloaded the new version, but nothing happens at all now when I save.

**Comment by daryltucker** [comment]
@reagle You're correct in that there is an issue with the Package Control version.  I manually installed my changes and it worked, but installing through Package Control causes an issue.

I will try making another change and seeing if this fixes the issue.

**Comment by daryltucker** [comment]
@reagle It seems to be working now.

1. Remove MagiclessQuotes
1. Close Sublime Text
1. Open Sublime Text
1. Install MagiclessQuotes

**Comment by reagle** [comment]
Soryry, it's still not changing anything upon saving.

**Comment by daryltucker** [comment]
@reagle Will you *View* > *Show Console* and see if you see any errors upon saving?

**Comment by reagle** [comment]
MagiclessQuote isn't even available to me anymore in package control?!?

**Comment by daryltucker** [comment]
Yikes!  I just removed and re-installed it via Package Control.  I've also tested it out on another machine to make sure it worked elsewhere.

Let me know if you're able to get it installed to troubleshoot and diagnose further.

**Comment by reagle** [comment]
Here's the error in the console.

````
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "magiclessquotes in /home/reagle/.config/sublime-text-3/Installed Packages/MagiclessQuotes.sublime-package", line 29, in run
TypeError: 'Region' object is not iterable
writing file /home/reagle/test.txt with encoding UTF-8 (atomic)
````

**Comment by reagle** [comment]
I just tested again (give that StraightQuotes seems to be [missing](https://bitbucket.org/directpartners/straightquotes)) and don't have the original bug or install problem.
